### ISSUE TITLE
describing what the bot exactly does

### ISSUE THREAD

**Issue by abdelhai** [DevolioDevChat/devolio-slackbot#4]

**Comment by EdenSG** [comment]
Just a quick draft:

> Hey there, ${name}, welcome to the Devolio Slack group!
> We'd love to hear a little about you - feel free to drop in on #intro and let everyone know what you're about.
> You can add your interests to your profile by [fill this out - I don't know what the easiest way to describe this is], and then you can join different channels for your various interests by clicking on that "Channels" link up near the top left [image of Channels link].
>
> This place is very community-driven - please don't be shy and speak up if you've got ideas! That said, all the regular social norms apply too (don't be a jerk) - but that should go without saying. Most importantly, though, have fun!
> Thanks!
> [some names? maybe? I don't know]
